CREATE TABLE IF NOT EXISTS streams (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    app VARCHAR(255) NOT NULL,
    stream_name VARCHAR(255) NOT NULL,
    stream_key VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'idle',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);



